# environment.yml
channels:
- conda-forge
dependencies:
- python =3.8
- pip
- pip:
  - py-entangle
- bio-embeddings-allennlp =0.9.2
- bio-embeddings-bepler =0.0.1
- bio-embeddings-CPCProt =0.0.1
- bio-embeddings-deepblast =0.1.0
- bio-embeddings-plus =0.1.1
- bio-embeddings-tape-proteins =0.5

